from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.home,
        name='home'
    ),
    path(
        'about/',
        views.about,
        name='about'
    ),
    path(
        'games/',
        views.games_index,
        name='games_index'
    ),
    path(
        'games/<int:game_id>/',
        views.games_detail,
        name='games_detail'
    ),
    path(
        'games/<int:game_id>/add_session',
        views.add_session,
        name='add_session'
    ),
    path(
        'games/create/',
        views.GameCreate.as_view(),
        name='games_create'
    ),
    path(
        'games/<int:pk>/update/',
        views.GameUpdate.as_view(),
        name='games_update'
    ),
    path(
        'games/<int:pk>/delete/',
        views.GameDelete.as_view(),
        name='games_delete'
    ),
    path(
        'games/<int:game_id>/include_venue/<int:venue_id>/',
        views.include_venue,
        name='include_venue'
    ),
    path(
        'games/<int:game_id>/exclude_venue/<int:venue_id>/',
        views.exclude_venue,
        name='exclude_venue'
    ),
    path(
        'venues/',
        views.EventVenueList.as_view(),
        name='venues_index'
    ),
    path(
        'venues/<int:pk>/',
        views.EventVenueDetail.as_view(),
        name='venues_detail'
    ),
    path(
        'venues/create/',
        views.EventVenueCreate.as_view(),
        name='venues_create'
    ),
    path(
        'venues/<int:pk>/update/',
        views.EventVenueUpdate.as_view(),
        name='venues_update'
    ),
    path(
        'venues/<int:pk>/delete/',
        views.EventVenueDelete.as_view(),
        name='venues_delete'
    ),
]
