# Generated by Django 5.0 on 2023-12-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('players', models.CharField(max_length=20)),
                ('playing_time', models.CharField(max_length=100)),
                ('complexity', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
