# Generated by Django 5.0 on 2024-01-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_game_options_gamesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['date']},
        ),
    ]
