# Generated by Django 5.0 on 2024-01-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_gamesession_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_players', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='venues',
            field=models.ManyToManyField(to='main_app.eventvenue'),
        ),
    ]
